
#pragma once

#define MSDFGEN_PUBLIC
#define MSDFGEN_EXT_PUBLIC

#define MSDFGEN_VERSION 10121
#define MSDFGEN_VERSION_MAJOR 1
#define MSDFGEN_VERSION_MINOR 12
#define MSDFGEN_VERSION_REVISION 1
#define MSDFGEN_COPYRIGHT_YEAR 2024

#define MSDFGEN_USE_CPP11
#define MSDFGEN_EXTENSIONS

